swagger: '2.0'
info:
  title: Inventory App
  version: ''
  description: >-
    Inventory App is a simple API to store Inventory transactions to the
    database
paths:
  /companies:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              - id: 1
                name: Example Company
                connectwiseid: example
                url: /companies/1
      summary: List all companies
      operationId: List all companies
      description: ''
      tags:
        - Companies
      parameters: []
      produces:
        - application/json
    put:
      responses:
        '200':
          description: OK
          headers:
            Location:
              type: string
          examples:
            application/json:
              id: 1
              name: Example Company
              connectwiseid: example
              url: /companies/1
      summary: Add a New Company
      operationId: Add a New Company
      description: |-
        Add a new company to track in the system.
        It takes a JSON object containing the necessary data
      tags:
        - Companies
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              connectwiseid:
                type: string
            example:
              name: Example Company
              connectwiseid: example
      produces:
        - application/json
  '/companies/{company_id}':
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              id: 1
              name: Example Company
              connectwiseid: example
              url: /companies/1
      summary: Get a Company
      operationId: Get a Company
      description: ''
      tags:
        - Companies
      parameters:
        - name: company_id
          in: path
          description: ''
          required: true
          type: number
      produces:
        - application/json
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Update a Company
      operationId: Update a Company
      description: Allows you to update the name or ConnectWise ID of a company
      tags:
        - Companies
      parameters:
        - name: company_id
          in: path
          description: ''
          required: true
          type: number
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: New comapny name
              connectwiseid:
                type: string
                description: New connectwiseid
            example:
              name: Example Company
              connectwiseid: example
  '/companies/{company_id}/users':
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              - id: 1
                first_name: John
                last_name: Smith
                full_name: John Smith
                url: /companies/1/users/1
      summary: Get all Users
      operationId: Get all Users
      description: ''
      tags:
        - Companies
      parameters:
        - name: company_id
          in: path
          description: ''
          required: true
          type: number
      produces:
        - application/json
    put:
      responses:
        '200':
          description: OK
          headers:
            Location:
              type: string
          examples:
            application/json:
              id: 1
              first_name: John
              last_name: Smith
              full_name: John Smith
              url: /companies/1/users/1
      summary: Add a New User
      operationId: Add a New User
      description: ''
      tags:
        - Companies
      parameters:
        - name: company_id
          in: path
          description: ''
          required: true
          type: number
      produces:
        - application/json
  '/companies/{company_id}/users/{user_id}':
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              id: 1
              first_name: John
              last_name: Smith
              full_name: John Smith
              url: /companies/1/users/1
      summary: Get a User
      operationId: Get a User
      description: ''
      tags:
        - Companies
      parameters:
        - name: company_id
          in: path
          description: ''
          required: true
          type: number
        - name: user_id
          in: path
          description: ''
          required: true
          type: number
      produces:
        - application/json
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Update a User
      operationId: Update a User
      description: ''
      tags:
        - Companies
      parameters:
        - name: company_id
          in: path
          description: ''
          required: true
          type: number
        - name: user_id
          in: path
          description: ''
          required: true
          type: number
        - name: body
          in: body
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
            example:
              first_name: John
              last_name: Smith
  /vendors:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              - id: 1
                name: Example Vendor
                account_number: EX12345
                url: /vendors/1
      summary: Get all vendors
      operationId: Get all vendors
      description: ''
      tags:
        - Vendors
      parameters: []
      produces:
        - application/json
    put:
      responses:
        '200':
          description: OK
          headers:
            Location:
              type: string
          examples:
            application/json:
              id: 1
              name: Example Vendor
              account_number: EX12345
              url: /vendors/1
      summary: Add a New Vendor
      operationId: Add a New Vendor
      description: ''
      tags:
        - Vendors
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              account_number:
                type: string
            example:
              name: Example Vendor
              account_number: EX12345
      produces:
        - application/json
  '/vendors/{vendor_id}':
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              id: 1
              name: Example Vendor
              account_number: EX12345
              url: /vendors/1
      summary: Get a Vendor
      operationId: Get a Vendor
      description: ''
      tags:
        - Vendors
      parameters:
        - name: vendor_id
          in: path
          description: ''
          required: true
          type: number
      produces:
        - application/json
    put:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Update a Vendor
      operationId: Update a Vendor
      description: ''
      tags:
        - Vendors
      parameters:
        - name: vendor_id
          in: path
          description: ''
          required: true
          type: number
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              account_number:
                type: string
            example:
              name: Example Vendor
              account_number: EX12345
  /orders:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              - id: 1
                order_number: EX12345
                vendor: 1
                date_ordered: '2021-12-31'
                total_cost: 99.99
                number_of_items: 5
                url: /orders/1
      summary: Get all Orders
      operationId: Get all Orders
      description: ''
      tags:
        - Orders
      parameters: []
      produces:
        - application/json
    put:
      responses:
        '200':
          description: OK
          headers:
            Location:
              type: string
          examples:
            application/json:
              id: 1
              order_number: EX12345
              vendor: 1
              date_ordered: '2021-12-31'
              total_cost: 99.99
              number_of_items: 5
              url: /orders/1
      summary: Record a New Order
      operationId: Record a New Order
      description: ''
      tags:
        - Orders
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              order_number:
                type: string
              vendor:
                type: number
              date_ordered:
                type: string
              total_cost:
                type: number
            example:
              order_number: EX12345
              vendor: 1
              date_ordered: '2021-12-31'
              total_cost: 99.99
      produces:
        - application/json
  '/orders/{order_id}':
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              id: 1
              order_number: EX12345
              vendor: 1
              date_ordered: '2021-12-31'
              total_cost: 99.99
              number_of_items: 5
              url: /orders/1
      summary: Get an Order
      operationId: Get an Order
      description: ''
      tags:
        - Orders
      parameters:
        - name: order_id
          in: path
          description: ''
          required: true
          type: number
      produces:
        - application/json
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Update an Order
      operationId: Update an Order
      description: ''
      tags:
        - Orders
      parameters:
        - name: order_id
          in: path
          description: ''
          required: true
          type: number
        - name: body
          in: body
          schema:
            type: object
            properties:
              order_number:
                type: string
              vendor:
                type: string
              date_ordered:
                type: string
              total_cost:
                type: number
            example:
              order_number: EX12345
              vendor: 1
              date_ordered: '2021-12-31'
              total_cost: 99.99
  '/orders/{order_id}/items':
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Get all Items
      operationId: Get all Items For An order
      description: ''
      tags:
        - Orders
      parameters:
        - name: order_id
          in: path
          description: ''
          required: true
          type: number
    put:
      responses:
        '200':
          description: OK
          headers:
            Location:
              type: string
          examples: {}
      summary: Add an Item
      operationId: Add an Item
      description: ''
      tags:
        - Orders
      parameters:
        - name: order_id
          in: path
          description: ''
          required: true
          type: number
  /items/:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Get all Items
      operationId: Get all Items
      description: ''
      tags:
        - Inventory Items
      parameters:
        - name: order_id
          in: query
          description: ''
          required: false
          type: number
        - name: received
          in: query
          description: ''
          required: false
          type: boolean
          default: 'True'
          enum:
            - 'True'
            - 'False'
        - name: checked_out
          in: query
          description: ''
          required: false
          type: boolean
          default: 'False'
          enum:
            - 'True'
            - 'False'
  '/items/{item_id}':
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples: {}
      summary: Update an Item
      operationId: Update an Item
      description: ''
      tags:
        - Inventory Items
      parameters:
        - name: item_id
          in: path
          description: ''
          required: true
          type: number
securityDefinitions: {}
tags:
  - name: Companies
  - name: Vendors
  - name: Orders
  - name: Inventory Items
